language: scala

scala:
  - 2.12.8

script:
  - sbt ++$TRAVIS_SCALA_VERSION scalafmtCheck test:scalafmtCheck scalafmtSbtCheck headerCheck test:headerCheck test

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
